# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 22:28
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()))),
        ),
    ]
