# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 20:23
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180116_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('post_heading', wagtail.wagtailcore.blocks.CharBlock(max_length=40)), ('section_heading', wagtail.wagtailcore.blocks.CharBlock(max_length=40)), ('inline_image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('code', wagtail.wagtailcore.blocks.StructBlock((('language', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('arduino', 'Arduino'), ('c', 'C'), ('css', 'CSS'), ('docker', 'Docker'), ('nginx', 'Nginx'), ('python', 'Python'), ('json', 'JSON'), ('yaml', 'YAML'), ('javascript', 'Javascript'), ('md', 'Markdown'), ('bash', 'Shell'), ('plpgsql', 'Pl/pgSQL'), ('postgresql', 'PostgreSQL'), ('sql', 'SQL'), ('sqlite3', 'SQLite3'), ('django', 'Django')])), ('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=['syntax', 'default'])), ('code', wagtail.wagtailcore.blocks.TextBlock())), icon='code')), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()))),
        ),
    ]
