# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 16:20
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180117_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('post_heading', wagtail.wagtailcore.blocks.CharBlock(max_length=40)), ('section_heading', wagtail.wagtailcore.blocks.CharBlock(max_length=40)), ('inline_image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('code', wagtail.wagtailcore.blocks.StructBlock((('language', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('arduino', 'Arduino'), ('bash', 'Shell'), ('c', 'C'), ('css', 'CSS'), ('django', 'Django'), ('docker', 'Docker'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('md', 'Markdown'), ('nginx', 'Nginx'), ('plpgsql', 'Pl/pgSQL'), ('postgresql', 'PostgreSQL'), ('python', 'Python'), ('sql', 'SQL'), ('sqlite3', 'SQLite3'), ('yaml', 'YAML')])), ('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('syntax', 'default')])), ('code', wagtail.wagtailcore.blocks.TextBlock())))), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()), ('left_aligned_image', wagtail.wagtailcore.blocks.StructBlock((('left_column', wagtail.wagtailcore.blocks.StreamBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()),))), ('right_column', wagtail.wagtailcore.blocks.StreamBlock((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()),)))))), ('right_aligned_image', wagtail.wagtailcore.blocks.StructBlock((('right_column', wagtail.wagtailcore.blocks.StreamBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()),))), ('left_column', wagtail.wagtailcore.blocks.StreamBlock((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()),)))))))),
        ),
    ]
