# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 21:37
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180117_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('post_heading', wagtail.wagtailcore.blocks.CharBlock(max_length=40)), ('section_heading', wagtail.wagtailcore.blocks.CharBlock(max_length=40)), ('inline_image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('code', wagtail.wagtailcore.blocks.StructBlock((('language', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('arduino', 'Arduino'), ('bash', 'Shell'), ('c', 'C'), ('css', 'CSS'), ('django', 'Django'), ('docker', 'Docker'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('md', 'Markdown'), ('nginx', 'Nginx'), ('plpgsql', 'Pl/pgSQL'), ('postgresql', 'PostgreSQL'), ('python', 'Python'), ('sql', 'SQL'), ('sqlite3', 'SQLite3'), ('yaml', 'YAML')])), ('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('syntax', 'default'), "('syntax', 'algol'),\n        ('syntax', 'algol_nu'),\n        ('syntax', 'arduino'),\n        ('syntax', 'autumn'),\n        ('syntax', 'borland'),\n        ('syntax', 'bw'),\n        ('syntax', 'colorful'),\n        ('syntax', 'emacs'),\n        ('syntax', 'friendly'),\n        ('syntax', 'fruity'),\n        ('syntax', 'igor'),\n        ('syntax', 'lovelace'),\n        ('syntax', 'manni'),\n        ('syntax', 'monokai'),\n        ('syntax', 'murphy'),\n        ('syntax', 'native'),\n        ('syntax', 'pastie'),\n        ('syntax', 'perldoc'),\n        ('syntax', 'rrt'),\n        ('syntax', 'solarized'),\n        ('syntax', 'solarized_dark'),\n        ('syntax', 'solarized_dark256'),\n        ('syntax', 'tango'),\n        ('syntax', 'trac'),\n        ('syntax', 'vim'),\n        ('syntax', 'vs'),\n        ('syntax', 'xcode'),"])), ('code', wagtail.wagtailcore.blocks.TextBlock())))), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()), ('left_aligned_image', wagtail.wagtailcore.blocks.StructBlock((('left_column', wagtail.wagtailcore.blocks.StreamBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()),))), ('right_column', wagtail.wagtailcore.blocks.StreamBlock((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()),)))))), ('right_aligned_image', wagtail.wagtailcore.blocks.StructBlock((('right_column', wagtail.wagtailcore.blocks.StreamBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()),))), ('left_column', wagtail.wagtailcore.blocks.StreamBlock((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()),)))))))),
        ),
    ]
