# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 14:31
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blog', '0027_auto_20180119_2139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostCategory',
            new_name='PostPageCategory',
        ),
        migrations.AddField(
            model_name='postpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.PostPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
